<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PrinterServices-119c6d44-b78c-4ac5-8838-59299cddfa07</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ESCPOS_NET" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlahiaPos.DataAccess\AlahiaPos.DataAccess.csproj" />
    <ProjectReference Include="..\AlahiaPos.Entities\AlahiaPos.Entities.csproj" />
  </ItemGroup>
</Project>
