<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AlahiaPos.DGII.Sync-1ede7bed-452f-4a6c-9869-a664e8fe29b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="11.0.0-preview.2.26159.112" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlahiaPos.DataAccess\AlahiaPos.DataAccess.csproj" />
    <ProjectReference Include="..\AlahiaPos.Entities\AlahiaPos.Entities.csproj" />
  </ItemGroup>
</Project>
