// <auto-generated />
using System;
using AlahiaPos.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlahiaPos.DataAccess.Migrations
{
    [DbContext(typeof(AlahiaPosContext))]
    [Migration("20260205132525_AddCorreoToCliente")]
    partial class AddCorreoToCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArea");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.AreaServicio", b =>
                {
                    b.Property<int>("IdAreaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAreaServicio"));

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAreaServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Categorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActiva")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Clientes", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<string>("CedulaRNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Cocinas", b =>
                {
                    b.Property<int>("IdCocina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCocina"));

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCocina");

                    b.ToTable("Cocinas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.CorreosElectronicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientesIDCliente")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientesIDCliente");

                    b.ToTable("CorreosElectronicos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoAreaDetalle", b =>
                {
                    b.Property<int>("IdDescuentoAreaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuentoAreaDetalle"));

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<int>("IdDescuentoHeader")
                        .HasColumnType("int");

                    b.HasKey("IdDescuentoAreaDetalle");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdDescuentoHeader");

                    b.ToTable("DescuentoAreaDetalle");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoDetalle", b =>
                {
                    b.Property<int>("IdDescuentoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuentoDetalle"));

                    b.Property<int>("IdDescuentoHeader")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdDescuentoDetalle");

                    b.HasIndex("IdDescuentoHeader");

                    b.HasIndex("IdProducto");

                    b.ToTable("DescuentoDetalle");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoHeader", b =>
                {
                    b.Property<int>("IdDescuentoHeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuentoHeader"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaATodasAreas")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaATodos")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDescuentoHeader");

                    b.ToTable("DescuentoHeader");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Empleados", b =>
                {
                    b.Property<int>("IdEmpleados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleados"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ComisionProductos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ComisionServicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpleados");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.EmpresaModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ModuloId");

                    b.ToTable("Empresa_Modulos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.EmpresaPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioBaseUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuariosIncluidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaPlan");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Empresas", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("CorreElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidPublico")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdPlanes")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TertiaryColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenNotificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCatalogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCitas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titleColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.FacturaDetalles", b =>
                {
                    b.Property<int>("IdFacturaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturaDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EnviadoCocina")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEmpleadoComision")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdFacturaHeader")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioOferta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("StatuItem")
                        .HasColumnType("bit");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFacturaDetalle");

                    b.HasIndex("IdFacturaHeader");

                    b.HasIndex("IdProducto");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.FacturaHeaders", b =>
                {
                    b.Property<int>("IdFacturaHeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturaHeader"));

                    b.Property<bool>("AjustadoInventario")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Efectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EstaCancelada")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaCerrada")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Orden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaBencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoComision")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleados")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<int?>("IdMoso")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDocumentos")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCheques")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoNotaCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPropina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTarjetaMasterCard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTarjetaVisa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTransferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NCF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PrintAcount")
                        .HasColumnType("bit");

                    b.Property<bool>("PrintPending")
                        .HasColumnType("bit");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFacturaHeader");

                    b.HasIndex("IDCliente");

                    b.ToTable("FacturaHeaders");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Gastos", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EstaCerrada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Orien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoGasto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGasto");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.HorariosEstilista", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("HorariosEstilistas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.ImpresorasZonas", b =>
                {
                    b.Property<int>("Impresoraid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Impresoraid"));

                    b.Property<string>("ImpresoraName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Impresoraid");

                    b.ToTable("ImpresorasZonas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Ingresos", b =>
                {
                    b.Property<int>("IdIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngreso"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdFacturaHeader")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdIngreso");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Mesas", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActiva")
                        .HasColumnType("bit");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("IdMesa");

                    b.HasIndex("ZonaId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.PagosFacturasClientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdFacturaHeader")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PagosFacturasClientes");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.ParametrosConfigs", b =>
                {
                    b.Property<int>("IdParametrosConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametrosConfig"));

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdParametrosConfig");

                    b.ToTable("ParametrosConfigs");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expira")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetToken");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.PerfilRoles", b =>
                {
                    b.Property<int>("IdPerfilRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfilRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.HasKey("IdPerfilRol");

                    b.HasIndex("IdModulo");

                    b.HasIndex("IdPerfil");

                    b.ToTable("PerfilRoles");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Perfiles", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPerfil");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.PlanSuscripcion", b =>
                {
                    b.Property<int>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlan"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPlan");

                    b.ToTable("PlanesSuscripcion");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Productos", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("ControlarStock")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DisponibleEnCitas")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Disponibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DuracionServicio")
                        .HasColumnType("int");

                    b.Property<bool?>("EsProductoBelleza")
                        .HasColumnType("bit");

                    b.Property<bool>("EsServicio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaVencimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<int?>("IdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdCocina")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("IdRecetasHeader")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Imagen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("Itbis")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcientoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcientoGanancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioDolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rentado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SeAlquila")
                        .HasColumnType("bit");

                    b.Property<bool>("SeCompra")
                        .HasColumnType("bit");

                    b.Property<bool>("SeVende")
                        .HasColumnType("bit");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoProducto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Zonas", b =>
                {
                    b.Property<int>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("ImpresoraId")
                        .HasColumnType("int");

                    b.Property<string>("ZonaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZonaId");

                    b.HasIndex("ImpresoraId");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaReciboPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCita");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("EmpleadoAreaComision", b =>
                {
                    b.Property<int>("IdEmpleadoAreaComision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoAreaComision"));

                    b.Property<DateTime>("FechaInseccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcientoComision")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEmpleadoAreaComision");

                    b.HasIndex("IdArea");

                    b.ToTable("EmpleadoAreaComision");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.CorreosElectronicos", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Clientes", null)
                        .WithMany("ClienteCorreos")
                        .HasForeignKey("ClientesIDCliente");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoAreaDetalle", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.DescuentoHeader", "Header")
                        .WithMany("Areas")
                        .HasForeignKey("IdDescuentoHeader")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Header");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoDetalle", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.DescuentoHeader", "Header")
                        .WithMany("Detalles")
                        .HasForeignKey("IdDescuentoHeader")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Empleados", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.EmpresaModulo", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany("EmpresaModulos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Modulo", "Modulo")
                        .WithMany("EmpresaModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.EmpresaPlan", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany("EmpresaPlanes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.FacturaDetalles", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.FacturaHeaders", "FacturaHeader")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("IdFacturaHeader")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Productos", "Productos")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaHeader");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.FacturaHeaders", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("IDCliente");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.HorariosEstilista", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empleados", "Estilista")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estilista");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Mesas", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Zonas", "zonas")
                        .WithMany("Mesas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("zonas");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.PerfilRoles", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Modulo", "Modulos")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Perfiles", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulos");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Perfiles", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Usuarios", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empleados", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Perfiles", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Empresa");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Zonas", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.ImpresorasZonas", "ImpresorasZonas")
                        .WithMany()
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImpresorasZonas");
                });

            modelBuilder.Entity("Cita", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Empleados", "Estilista")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Empresas", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlahiaPos.Entities.Domain.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Estilista");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("EmpleadoAreaComision", b =>
                {
                    b.HasOne("AlahiaPos.Entities.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Clientes", b =>
                {
                    b.Navigation("ClienteCorreos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.DescuentoHeader", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Empresas", b =>
                {
                    b.Navigation("EmpresaModulos");

                    b.Navigation("EmpresaPlanes");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.FacturaHeaders", b =>
                {
                    b.Navigation("FacturaDetalles");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Modulo", b =>
                {
                    b.Navigation("EmpresaModulos");
                });

            modelBuilder.Entity("AlahiaPos.Entities.Domain.Zonas", b =>
                {
                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
